export {
  createHeartAttackGame,
  flipHeartAttackCard,
  chooseWildFruit,
  slapHeartAttack,
  buildDeck,
  computeFruitTotals,
  isBellActive,
  emptyFruitTotals,
  pickBestWildFruit,
  generateBotWildChoice,
  generateBotShouldSlap,
  redactHeartAttackState,
  cardLabel,
  ALL_FRUITS,
  FRUIT_LABELS,
  FRUIT_EMOJI,
  type HeartAttackGameState,
  type HeartAttackPlayerState,
  type HeartAttackCard,
  type HeartAttackLastAction,
  type HeartAttackPhase,
  type HeartAttackStage,
  type Fruit,
  type CardKind,
} from './logic.js';
export { heartAttackModule, type HeartAttackStartOptions } from './module.js';
